name: Manual Greeting

on:
  workflow_dispatch:
    inputs:
      student_name:
        description: "Имя ученика для приветствия"
        required: true
        default: "Школьник"

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: T1
        run: echo "Hi, ${{ inputs.student_name }}!"

      - name: T2
        run: echo "The number is $GITHUB_RUN_NUMBER"

      # TODO:
      # 1. Добавь шаг, который выводит приветствие для inputs.student_name
      # 2. Попробуй дополнительно вывести номер запуска: GITHUB_RUN_NUMBER
